# Numpy

In [ ]:
import numpy as np

In [5]:
def create_ndarray_object():
    arr_from_list = np.array([1,2,3,4,5])
    arr_from_tuple = np.array((1,2,3,4,5))
    print("arr_from_list = ",arr_from_list)
    print("arr_from_tuple = ",arr_from_tuple)
    print("type(arr_from_list) = ",type(arr_from_list))
    print("type(arr_from_tuple) = ",type(arr_from_tuple))
    
create_ndarray_object()

arr_from_list =  [1 2 3 4 5]
arr_from_tuple =  [1 2 3 4 5]
type(arr_from_list) =  <class 'numpy.ndarray'>
type(arr_from_tuple) =  <class 'numpy.ndarray'>


In [7]:
def dimensions_in_arrays():
    arr_0D = np.array(5)
    arr_1D = np.array([1,2,3,4,5])
    arr_2D = np.array([[1,2,3],[4,5,6]])
    print("arr_0D = ", arr_0D)
    print("arr_1D = ", arr_1D)
    print("arr_2D = ", arr_2D)
    
    print("Demension of arr_0D = ",arr_0D.ndim)
    print("Demension of arr_1D = ",arr_1D.ndim)
    print("Demension of arr_2D = ",arr_2D.ndim)

dimensions_in_arrays()

arr_0D =  5
arr_1D =  [1 2 3 4 5]
arr_2D =  [[1 2 3]
 [4 5 6]]
Demension of arr_0D =  0
Demension of arr_1D =  1
Demension of arr_2D =  2


In [8]:
def indexing_and_slicing():
    arr_1D = np.array([1,2,3,4])
    arr_2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
    print("1st element = ", arr_1D[0])
    print("2nd element on 1st dimension = ", arr_2D[1,3])
    
    #1-D Array
    arr_1D = np.array([1,2,3,4,5,6,7,8,9,10])
    print("Slice lements from index 1 to index 5 = ", arr_1D[1:5])
    print("Slice lements from index 3 to the end = ", arr_1D[3:])
    print("Use the step value to return every other element from index 1 to index 5 = ", arr_1D[1:5:2])
    print("Return every other element from the entire array: ", arr_1D[::2])
    
    #2-D Array
    arr_2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
    print("Slice index 1 to index 4 (not incluede)from the second element", arr_2D[1,1:4])
    print("From both elements, return index 2: ", arr_2D[0:2,2])
    print("From both elements, slice index 1 to index 4 (not included): ",arr_2D[0:2,1:4])
    
indexing_and_slicing()

1st element =  1
2nd element on 1st dimension =  9
Slice lements from index 1 to index 5 =  [2 3 4 5]
Slice lements from index 3 to the end =  [ 4  5  6  7  8  9 10]
Use the step value to return every other element from index 1 to index 5 =  [2 4]
Return every other element from the entire array:  [1 3 5 7 9]
Slice index 1 to index 4 (not incluede)from the second element [7 8 9]
From both elements, return index 2:  [3 8]
From both elements, slice index 1 to index 4 (not included):  [[2 3 4]
 [7 8 9]]


In [9]:
def checking():
    arr_integer = np.array([1,2,3,4])
    arr_string = np.array(['apple','bnana','cherry'])
    
    print(arr_integer.dtype)
    print(arr_string.dtype)
    
checking()

int64
<U6


In [11]:
def creating():
    #Create an array with data type string:
    arr_S = np.array([1,2,3,4], dtype='S')
    
    #Create an array with data type 4 bytes integer:
    arr_i4 = np.array([1,2,3,4],dtype='i4')
    
    print(arr_S)
    print(arr_S.dtype)
    print(arr_i4)
    print(arr_i4.dtype)
    
creating()

[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32


In [13]:
def converting_datatype():
    arr1 = np.array([1.1,2.1,3.1])
    #Change data type from float to integer by using 'i' as parameter value:
    newarr11 = arr1.astype('i')
    #Change data type from float to integer by using int as parameter value:
    newarr12 = arr1.astype(int)

    #Change data type from integer to boolean:
    arr2 = np.array([1,0,3])
    newarr2 = arr2.astype(bool)
    
    print(newarr11)
    print(newarr11.dtype)
    print(newarr12)
    print(newarr12.dtype)
    print(newarr2)
    print(newarr2.dtype)

converting_datatype()

[1 2 3]
int32
[1 2 3]
int64
[ True False  True]
bool


In [14]:
def copy_function():
    arr = np.array([1,2,3,4,5])
    arr_copy = arr.copy()
    arr[0] = 10
    
    print("Original array: ", arr)
    print("Copy array: ", arr_copy)

copy_function()

Original array:  [10  2  3  4  5]
Copy array:  [1 2 3 4 5]


In [15]:
def shape_function():
    arr = np.array([[1,2,3,4],[5,6,7,8]])
    print("Shape of array = ", arr.shape)
    
shape_function()

Shape of array =  (2, 4)


In [17]:
def reshape_function():
    arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
    newarr = arr.reshape(4,3)
    print(newarr)

reshape_function()

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
def interating():
    
    arr = np.array([[1,2,3],[4,5,6]])
    
    print("Method 1:")
    for x in arr:
        for y in x:
            print(y)
            
    print("-----")
    print("Method 2:")
    for x in np.nditer(arr):
        print(x)
    for idx,x in np.ndenumerate(arr):
        print(idx,x)
        
interating()

Method 1:
1
2
3
4
5
6
-----
Method 2:
1
2
3
4
5
6
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [20]:
def join_function():
    print("1-D array")
    arr1 = np.array([1,2,3])
    arr2 = np.array([4,5,6])
    arr = np.concatenate((arr1,arr2))
    print(arr)
    
    print("-----")
    print("2-D array")
    arr1 = np.array([[1,2],[3,4]])
    arr2 = np.array([[5,6],[7,8]])
    arr = np.concatenate((arr1,arr2),axis=1)
    print(arr)
    
    print("stack()")
    arr1 = np.array([1,2,3])
    arr2 = np.array([4,5,6])
    arr = np.stack((arr1,arr2),axis=1)
    
    print("Stacking Along Rows: hstack()")
    arr = np.hstack((arr1,arr2))
    print(arr)
    
    print("Stacking Along Columns: vstack()")
    arr = np.vstack((arr1,arr2))
    print(arr)
    
    print("Stack Along Height(depth): dstack()")
    arr = np.dstack((arr1,arr2))
    print(arr)
    
join_function()

1-D array
[1 2 3 4 5 6]
-----
2-D array
[[1 2 5 6]
 [3 4 7 8]]
stack()
Stacking Along Rows: hstack()
[1 2 3 4 5 6]
Stacking Along Columns: vstack()
[[1 2 3]
 [4 5 6]]
Stack Along Height(depth): dstack()
[[[1 4]
  [2 5]
  [3 6]]]


In [21]:
def split_function():
    print("Split 1-D array in 3 parts: ")
    arr = np.array([1,2,3,4,5,6])
    newarr = np.array_split(arr,3)
    print(newarr)
    print(newarr[0])
    print(newarr[1])
    print(newarr[2])
    
    print("-----")
    arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
    print("Split the 2-D array into three 2-D arrays:")
    newarr = np.array_split(arr,3)
    print(newarr)
    print("Split the 2-D array into three 2-D arrays along rows:")
    newarr = np.array_split(arr,3,axis=1)
    print(newarr)

split_function()

Split 1-D array in 3 parts: 
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
-----
Split the 2-D array into three 2-D arrays:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
Split the 2-D array into three 2-D arrays along rows:
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [23]:
def search_function():
    arr = np.array([1,2,3,4,5,4,4])
    print("The indexes where the value is 4: ")
    x= np.where(arr ==4)
    print(x)
    
    print("The indexes where the values are odd:")
    x = np.where(arr%2==1)
    print(x)
    
    arr = np.array([6,7,8,9])
    print("The indexes where the value 7 should be inserted: ")
    x = np.searchsorted(arr,7)
    print(x)
    
    print("The indexes where the value 7 should be inserted, starting from the right: ")
    x = np.searchsorted(arr,7,side='right')
    print(x)
    
    print("The indexes where multiple values should be inserted:")
    arr = np.array([1,3,5,7])
    x = np.searchsorted(arr,[2,4,6])
    print(x)
    
search_function()

The indexes where the value is 4: 
(array([3, 5, 6]),)
The indexes where the values are odd:
(array([0, 2, 4]),)
The indexes where the value 7 should be inserted: 
1
The indexes where the value 7 should be inserted, starting from the right: 
2
The indexes where multiple values should be inserted:
[1 2 3]


In [24]:
def sort_function():
    print("Sort numeric array:")
    arr = np.array([3,2,0,1])
    print(np.sort(arr))
    
    print("Sort string array:")
    arr = np.array(['bnana','cherry','apple'])
    print(np.sort(arr))
    
    print("Sort boolean array:")
    arr = np.array([True, False, True])
    print(np.sort(arr))
    
    print("Sort 2-D array:")
    arr = np.array([[3,2,4],[5,0,1]])
    print(np.sort(arr))
    
sort_function()

Sort numeric array:
[0 1 2 3]
Sort string array:
['apple' 'bnana' 'cherry']
Sort boolean array:
[False  True  True]
Sort 2-D array:
[[2 3 4]
 [0 1 5]]


In [26]:
from numpy import random
def random_numbers():
    print("Generate a random integer from 0 to 100: ")
    x = random.randint(100)
    
    print("Generate a random float from 0 to 1: ")
    x = random.rand()
    print(x)
    
    print("Generate a 1-D array containing 5 random integers from 0 to 100: ")
    x = random.randint(100,size=(5))
    print(x)
    
    print("Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:")
    x = random.randint(100, size=(3,5))
    print(x)
    
    print("Generate a 1-D array containing 5 random floats:")
    x = random.rand(5)
    print(x)
    
    print("Generate a 2-D array with 3 rows, each row containing 5 random numbers: ")
    x = random.rand(3,5)
    print(x)
    
    x = random.choice([3,5,7,9])
    print("Return one of the values in an array: ", x)
    
    x = random.choice([3,5,7,9], size=(3,5))
    print("Generate a 2-D array that consists of the values in the array parameter (3,5,7, and 9): ",x)
    
random_numbers()

Generate a random integer from 0 to 100: 
Generate a random float from 0 to 1: 
0.9716633473299956
Generate a 1-D array containing 5 random integers from 0 to 100: 
[56 18 21 74 49]
Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
[[93 48 61 17 53]
 [30 61 70 34 39]
 [ 9 18 71  2 52]]
Generate a 1-D array containing 5 random floats:
[0.14942737 0.00921923 0.2263519  0.81694408 0.17276976]
Generate a 2-D array with 3 rows, each row containing 5 random numbers: 
[[0.09275237 0.3085184  0.19596583 0.59247683 0.68422927]
 [0.96735486 0.80103133 0.28283616 0.27100849 0.32170297]
 [0.63440882 0.59380554 0.84191676 0.05142233 0.63234633]]
Return one of the values in an array:  9
Generate a 2-D array that consists of the values in the array parameter (3,5,7, and 9):  [[7 5 5 9 5]
 [7 5 5 7 7]
 [5 5 5 9 5]]


In [27]:
def random_permutations():
    arr = np.array([1,2,3,4,5])
    random.shuffle(arr)
    print(arr)
    arr = np.array([1,2,3,4,5])
    print(random.permutation(arr))

random_permutations()

[5 3 4 2 1]
[4 1 5 2 3]


# Pandas

In [29]:
import pandas as pd

In [30]:
def pandas_series():
    a = [1,10,5]
    SimpleSeries = pd.Series(a)
    print(SimpleSeries)
    print("1st value: ",SimpleSeries[0])
    print("2nd value: ",SimpleSeries[1])
    
    print("-----")
    NamedSeries = pd.Series(a, index = ["x","y","z"])
    print("Naming the labels: ")
    print(NamedSeries)
    print("The value of y : ", NamedSeries["y"])
    
pandas_series()

0     1
1    10
2     5
dtype: int64
1st value:  1
2nd value:  10
-----
Naming the labels: 
x     1
y    10
z     5
dtype: int64
The value of y :  10


In [32]:
def pandas_dataframe():
    data = {"calories":[420,380,390],"duration":[50,40,45]}
    #load data into a DataFrame object:
    df = pd.DataFrame(data)
    print(df)
    print("Row 0 :")
    print(df.loc[0])
    print("Row 1 :")
    print(df.loc[1])
    print("Row 0 and 1 :")
    print(df.loc[[0,1]])
    #named indexes
    df = pd.DataFrame(data,index = ["day1","day2","day3"])
    print(df)
    print("day2: ")
    print(df.loc["day2"])
    
    df = pd.read_csv('data.csv')
    
    print("The first 5 rows: ")
    print(df.head())
    
    print("\n")
    print("The last 5 rows: ")
    print(df.tail())
    
    print("\n")
    print("Information about the data: ")
    print(df.info())
    
pandas_dataframe()

   calories  duration
0       420        50
1       380        40
2       390        45
Row 0 :
calories    420
duration     50
Name: 0, dtype: int64
Row 1 :
calories    380
duration     40
Name: 1, dtype: int64
Row 0 and 1 :
   calories  duration
0       420        50
1       380        40
      calories  duration
day1       420        50
day2       380        40
day3       390        45
day2: 
calories    380
duration     40
Name: day2, dtype: int64
The first 5 rows: 
   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


The last 5 rows: 
     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4


Information about the d